apiVersion: v1
kind: Service
metadata:
  name: operator-api
  namespace: dataspace
spec:
  selector:
    app: operator-api
  ports:
    - name: "operator-api8050"
      port: 8050
      targetPort: 8050
