apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ipfs-data-pvc
  namespace: dataspace
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
