apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: dataspace
  labels:
    app: postgres
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: postgresadmin
  POSTGRES_PASSWORD: postgresadminpass
  POSTGRES_HOST: postgres.dataspace
  POSTGRES_PORT: "5432"
  PGDATA: /var/lib/postgresql/data/pgdata
