apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ocean-compute-operator
  name: ocean-compute-operator
  namespace: dataspace
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ocean-compute-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ocean-compute-operator
    spec:
      containers:
      - env:
        - name: maxJobs
          value: "1"
        - name: nCPU
          value: "2"
        - name: ramGB
          value: "4"
        - name: diskGB
          value: "1"
        - name: nGPU
          value: "0"
        - name: maxJobDuration
          value: "900"
        - name: priceMinute
          value: "0.01"
        - name: IPFS_OUTPUT
          value: http://ipfs.dataspace:5001
        - name: IPFS_OUTPUT_PREFIX
          value: https://ipfs.local/ipfs/
        - name: IPFS_ADMINLOGS
          value: http://ipfs.dataspace:5001
        - name: IPFS_ADMINLOGS_PREFIX
          value: https://ipfs.local/ipfs/
        - name: IPFS_EXPIRY_TIME
          value: "3600"
        - name: STORAGE_CLASS
          value: standard
        - name: LOG_LEVEL
          value: DEBUG
        - name: OPERATOR_PRIVATE_KEY
          value: "0x0000000000000000000000000000000000000000000000000000000000000001"
        - name: POD_CONFIGURATION_CONTAINER
          value: rogargon/pod-configuration:timeout
        - name: POD_PUBLISH_CONTAINER
          value: oceanprotocol/pod-publishing:v4main
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_DB
              name: postgres-config
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_USER
              name: postgres-config
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_PASSWORD
              name: postgres-config
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_HOST
              name: postgres-config
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_PORT
              name: postgres-config
        image: rogargon/operator-engine:gke-gpu
        imagePullPolicy: Always
        name: ocean-compute-operator
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccountName: operator
      terminationGracePeriodSeconds: 30
