apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: operator-binding
  namespace: dataspace
subjects:
  - kind: ServiceAccount
    name: operator
    namespace: dataspace
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: operatorRole
  apiGroup: rbac.authorization.k8s.io
